navbar:
  blog_title: "Fogpost"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "rss", link: "/rss.xml", icon: "iconfont icon-rss", name: "è®¢é˜…" }
    #- { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }

# lazyload:
#   enable: true
#   loading_img: /img/loading.gif
#   onlypost: true
#   offset_factor: 2

rss:
  enable: true
  limit: 20
  content: true
  # ðŸ‘‡ å…³é”®
  highlight: false

